language: node_js
node_js:
  - '8'
notifications: # 성공 실패 여부 알림
  email:
    recipients:
      - rb7480@naver.com
cache:
  directories:
    - 'node_modules'
branches:
  only:
    - master
    - develop
install:
  - npm i -g travis-ci-cloudfront-invalidation
  - cp .env.production .env
  - cat .env
  - npm install
  - npm run generate
script:
  - echo "Skipping tests"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ceo.cheolgyu.com
    region: ap-northeast-2
    local_dir: dist
    skip_cleanup: true
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ceo.cheolgyu.com
    region: ap-northeast-2
    local_dir: dist
    skip_cleanup: true
    on:
      branch: develop
    
after_deploy: 
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $CF_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST